steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/cloudbuilddemo:$SHORT_SHA
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/cloudbuilddemo:$SHORT_SHA
  - name: google/cloud-sdk
    args:
      - gcloud
      - run
      - deploy
      - cloudbuild-dotnet-demo
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/cloudbuilddemo:$SHORT_SHA'
      - '--region'
      - us-central1
      - '--platform'
      - managed
      - '--allow-unauthenticated'
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/cloudbuilddemo:$SHORT_SHA
options:
  logging: NONE